"""
Phase 3C-1: Structure modeling interface layer.

Generates structure modeling tasks for CDRH3 candidates, outputs
manifests and provenance records.  Supports dry_run (plan only)
and mock (placeholder PDB) modes for environments without
NanoBodyBuilder2 / OpenMM.

Never outputs ddG, Kd, binding affinity, validated, or
experimentally-confirmed claims.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


# ═══════════════════════════════════════════════════════════════
# Modeling risk by CDRH3 length
# ═══════════════════════════════════════════════════════════════

def _modeling_risk(length: int) -> Dict[str, Any]:
    if length < 8:
        return {"level": "blocking", "reason": f"CDRH3 too short for reliable modeling: {length}aa < 8"}
    elif length <= 18:
        return {"level": "low", "reason": f"CDRH3 length {length}aa within standard VHH range"}
    elif length <= 24:
        return {"level": "moderate", "reason": f"CDRH3 length {length}aa — longer loops have higher conformational entropy"}
    elif length <= 30:
        return {"level": "high", "reason": f"CDRH3 length {length}aa — very long loops may not converge"}
    else:
        return {"level": "blocking", "reason": f"CDRH3 too long for reliable modeling: {length}aa > 30"}


# ═══════════════════════════════════════════════════════════════
# Mock PDB generator
# ═══════════════════════════════════════════════════════════════

_MOCK_PDB_TEMPLATE = """REMARK  MOCK STRUCTURE — NOT FOR SCIENTIFIC USE
REMARK  DO NOT USE FOR DOCKING OR SCIENTIFIC INTERPRETATION
REMARK  Generated by Biochat Phase 3C-2 (structure_modeling.py)
REMARK  NanoBodyBuilder2 environment not available on this machine.
REMARK  This is a PLACEHOLDER — no real folding was performed.
REMARK  mock=true  not_for_scientific_use=true  eligible_for_docking=false
REMARK  Generated: {timestamp}
REMARK  Method: mock_placeholder
REMARK  Candidate: {candidate_id}
REMARK  CDRH3: {cdrh3_sequence}
REMARK  Framework: {framework}
ATOM      1  CA  ALA A   1       0.000   0.000   0.000  1.00  0.00           C
ATOM      2  CA  ALA A   2       3.800   0.000   0.000  1.00  0.00           C
TER
END
"""


def _write_mock_pdb(
    candidate_id: str,
    cdrh3_sequence: str,
    framework: str,
    output_path: str,
) -> str:
    """Write a placeholder PDB file. Returns the file path."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    content = _MOCK_PDB_TEMPLATE.format(
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        candidate_id=candidate_id,
        cdrh3_sequence=cdrh3_sequence,
        framework=framework,
    )
    with open(output_path, "w") as fh:
        fh.write(content)
    return output_path


# ═══════════════════════════════════════════════════════════════
# Public API
# ═══════════════════════════════════════════════════════════════

def build_vh_structures(
    candidates: List[Dict[str, Any]],
    output_dir: str,
    method: str = "nanobodybuilder2",
    framework: str = "IGHV3-23",
    dry_run: bool = False,
    mock: bool = False,
    allow_mock_fallback: bool = False,
) -> Dict[str, Any]:
    """Build VH-only structure modeling tasks for CDRH3 candidates.

    Args:
        candidates: Phase 3C-0 candidates with structure_readiness fields.
        output_dir: Output directory for manifest and structure files.
        method: Modeling method name (default: nanobodybuilder2).
        framework: IGHV framework for grafting.
        dry_run: If True, only plan — no files written except manifest.
        mock: If True, generate placeholder PDB files.

    Returns:
        {
            "manifest": {...},
            "candidates": [{...per-candidate modeling result...}],
            "provenance": "computed",
            "calibration": "uncalibrated",
        }
    """
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, "inputs"), exist_ok=True)
    structures_dir = os.path.join(output_dir, "structures")
    if not dry_run:
        os.makedirs(structures_dir, exist_ok=True)

    # Check NanoBodyBuilder2 availability via dedicated adapter
    from biomni.tool.antibody_design.nanobodybuilder2_adapter import check_nanobodybuilder2_available
    nb2_info = check_nanobodybuilder2_available()
    nb2_available = nb2_info["available"]

    # Determine if we should use mock
    use_mock = mock or (allow_mock_fallback and not nb2_available)
    fallback_reason = None
    if not mock and allow_mock_fallback and not nb2_available:
        fallback_reason = "NanoBodyBuilder2 not available; mock fallback enabled via allow_mock_fallback=True"

    # If real method requested but NB2 unavailable and no fallback → fail
    if not dry_run and not use_mock and not nb2_available:
        # Return failure manifest — no structures generated
        manifest = _make_manifest(output_dir, method, framework, dry_run, False, nb2_available,
                                  total=len(candidates), planned=0, success=0, skipped=0, failed=len(candidates))
        failed_candidates = []
        for c in candidates:
            cid = c.get("cdrh3_sequence", "?")[:30]
            failed_candidates.append({
                "candidate_id": cid,
                "attempted": True, "available": False,
                "method": method, "status": "failed",
                "provenance": "computed", "calibration": "uncalibrated",
                "output_pdb": None, "mock": False,
                "not_for_scientific_use": False,
                "eligible_for_docking": False,
                "modeling_risk": _modeling_risk(len(cid)),
                "warnings": [],
                "errors": ["NanoBodyBuilder2 not available. Use mock=True or allow_mock_fallback=True."],
            })
        manifest["candidates"] = failed_candidates
        _write_manifest(output_dir, manifest)
        return manifest

    results: List[Dict[str, Any]] = []
    planned_count = 0
    success_count = 0
    skipped_count = 0
    failed_count = 0

    for c in candidates:
        cid = c.get("candidate_id") or c.get("cdrh3_sequence", f"candidate_{c.get('index', '?')}")
        cdrh3_seq = c.get("cdrh3_sequence", cid)
        length = len(cdrh3_seq)
        risk = _modeling_risk(length)
        ready = c.get("ready", True)
        blocking = c.get("blocking_issues", [])

        modeling: Dict[str, Any] = {
            "candidate_id": cid[:30],
            "attempted": False,
            "available": nb2_available,
            "method": method if nb2_available else "mock",
            "provenance": "computed",
            "calibration": "uncalibrated",
            "status": "skipped",
            "output_pdb": None,
            "modeling_risk": risk,
            "warnings": [],
            "errors": [],
            "mock": False,
            "not_for_scientific_use": False,
            "eligible_for_docking": False,
            "fallback_reason": fallback_reason,
        }

        # Skip blocked candidates
        if not ready or blocking:
            modeling["status"] = "skipped"
            modeling["errors"] = list(blocking)
            skipped_count += 1
            results.append(modeling)
            continue

        # Skip if risk is blocking (length outside 8-30)
        if risk["level"] == "blocking":
            modeling["status"] = "skipped"
            modeling["errors"].append(f"modeling_risk_blocking: {risk['reason']}")
            skipped_count += 1
            results.append(modeling)
            continue

        # Attempt modeling
        modeling["attempted"] = True

        if dry_run:
            modeling["status"] = "planned"
            modeling["warnings"].append("dry_run: no structure generated")
            planned_count += 1
            results.append(modeling)
            continue

        if use_mock:
            # Mock mode: generate placeholder PDB (explicitly requested or fallback)
            pdb_path = os.path.join(structures_dir, f"candidate_{int(c.get('index', 0))+1:03d}.pdb")
            try:
                _write_mock_pdb(cid, cdrh3_seq, framework, pdb_path)
                modeling["status"] = "success"
                modeling["output_pdb"] = pdb_path
                modeling["method"] = "mock"
                modeling["mock"] = True
                modeling["not_for_scientific_use"] = True
                modeling["eligible_for_docking"] = False
                msg = "mock_structure: placeholder PDB, NOT a real folded structure."
                if fallback_reason:
                    msg += f" (fallback: {fallback_reason})"
                modeling["warnings"].append(msg)
                success_count += 1
            except Exception as exc:
                modeling["status"] = "failed"
                modeling["errors"].append(str(exc))
                failed_count += 1
        elif nb2_available:
            # Phase 3C-3: Real NanoBodyBuilder2 prediction
            from biomni.tool.antibody_design.nanobodybuilder2_adapter import (
                construct_vh_sequence_from_cdrh3, predict_nanobody_structure,
            )

            # Build full VH sequence or use provided one
            vh_seq = c.get("vh_sequence", "")
            seq_meta = {}
            if not vh_seq:
                try:
                    seq_info = construct_vh_sequence_from_cdrh3(cdrh3_seq, framework)
                    vh_seq = seq_info["vh_sequence"]
                    seq_meta = seq_info
                except Exception as exc:
                    modeling["status"] = "failed"
                    modeling["errors"].append(f"sequence_construction_failed: {exc}")
                    failed_count += 1
                    results.append(modeling)
                    continue
            else:
                seq_meta = {"provenance": "provided", "vh_sequence": vh_seq}

            modeling["sequence_construction"] = seq_meta

            # Run real prediction
            pdb_path = os.path.join(structures_dir, f"candidate_{int(c.get('index', 0))+1:03d}.pdb")
            pred = predict_nanobody_structure(vh_seq, pdb_path)

            if pred["success"]:
                modeling["status"] = "success"
                modeling["output_pdb"] = pred["output_pdb"]
                modeling["method"] = pred["method"]
                modeling["mock"] = False
                modeling["not_for_scientific_use"] = False
                modeling["structure_type"] = "predicted_model"
                modeling["experimental_support"] = "none"

                # PDB validation
                from biomni.tool.antibody_design.structure_validation import validate_pdb_for_docking
                pdb_val = validate_pdb_for_docking(pred["output_pdb"])
                modeling["pdb_validation"] = pdb_val
                modeling["eligible_for_docking"] = pdb_val.get("eligible_for_docking", False)
                success_count += 1
            else:
                modeling["status"] = "failed"
                modeling["errors"].append(
                    f"{pred.get('error_type', 'unknown')}: {pred.get('error_message', 'no detail')}"
                )
                failed_count += 1
        # else: nb2 unavailable, no fallback → was caught earlier (pre-loop failure)

        results.append(modeling)

    # Build manifest
    full_output = _make_manifest(
        output_dir, method, framework, dry_run, use_mock, nb2_available,
        total=len(candidates), planned=planned_count,
        success=success_count, skipped=skipped_count, failed=failed_count,
    )
    full_output["candidates"] = results

    _write_manifest(output_dir, full_output)

    # Write FASTA
    fasta_path = os.path.join(output_dir, "inputs", "candidates.fasta")
    lines = []
    for i, c in enumerate(candidates, 1):
        seq = c.get("cdrh3_sequence", "")
        lines.append(f">candidate_{i:03d}|CDRH3|len={len(seq)}|framework={framework}")
        lines.append(seq)
    if not dry_run:
        with open(fasta_path, "w") as fh:
            fh.write("\n".join(lines) + "\n")

    return full_output


def _make_manifest(output_dir, method, framework, dry_run, mock, nb2_available,
                   total, planned, success, skipped, failed):
    return {
        "manifest": {
            "manifest_version": "3C-3",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "output_dir": os.path.abspath(output_dir),
            "method": method,
            "framework": framework,
            "dry_run": dry_run,
            "mock": mock,
            "nanobodybuilder2_available": nb2_available,
            "total_candidates": total,
            "planned": planned,
            "success": success,
            "skipped": skipped,
            "failed": failed,
            "provenance": "computed",
            "calibration": "uncalibrated",
            "disclaimer": (
                "All structure models are computational predictions. "
                "Mock structures are PLACEHOLDERS — no real folding was performed. "
                "No binding affinity, ΔG, Kd, or experimental validation is implied."
            ),
        },
        "provenance": "computed",
        "calibration": "uncalibrated",
    }


def _write_manifest(output_dir, full_output):
    manifest_path = os.path.join(output_dir, "structure_modeling_manifest.json")
    with open(manifest_path, "w") as fh:
        json.dump(full_output, fh, indent=2, ensure_ascii=False)


# ═══════════════════════════════════════════════════════════════
# Environment check — delegated to nanobodybuilder2_adapter.py
# ═══════════════════════════════════════════════════════════════
