"""
Phase 3C-4: Docking input preparation — receptor, ligand, constraints.

Prepares PDB files and constraint specs for downstream docking.
Does NOT execute docking, does NOT call HDOCK/PyRosetta.
All outputs are labeled as uncalibrated computational constructs.
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List

from biochat.tool.antibody_design.structure_validation import validate_pdb_for_docking

VALID_AAS = set("ACDEFGHIKLMNPQRSTVWY")
_EPS = 3.8  # Å spacing for extended peptide CA atoms


def _sanitize_id(raw: str) -> str:
    """Sanitize a candidate ID for use in filenames."""
    import re
    safe = re.sub(r'[^a-zA-Z0-9_-]', '_', str(raw))[:60]
    return safe or "unknown"

_AA1TO3 = {
    "A": "ALA", "C": "CYS", "D": "ASP", "E": "GLU", "F": "PHE",
    "G": "GLY", "H": "HIS", "I": "ILE", "K": "LYS", "L": "LEU",
    "M": "MET", "N": "ASN", "P": "PRO", "Q": "GLN", "R": "ARG",
    "S": "SER", "T": "THR", "V": "VAL", "W": "TRP", "Y": "TYR",
}


# ═══════════════════════════════════════════════════════════════
# Ligand: extended peptide PDB builder
# ═══════════════════════════════════════════════════════════════

_EXTENDED_PEPTIDE_REMARK = (
    "REMARK  EXTENDED PEPTIDE — INITIAL COMPUTATIONAL CONSTRUCT\n"
    "REMARK  Generated by Biochat Phase 3C-4 (docking_prep.py)\n"
    "REMARK  This is NOT an experimentally determined structure.\n"
    "REMARK  Coordinates: ideal extended chain, 3.8 Å CA-CA spacing.\n"
    "REMARK  Use only as initial docking input — expect conformational\n"
    "REMARK  rearrangement upon binding.\n"
    "REMARK  experimental_support=none  calibration=uncalibrated\n"
)


def build_extended_peptide_pdb(
    sequence: str,
    output_pdb: str,
    chain_id: str = "A",
) -> Dict[str, Any]:
    """Build a simple extended peptide PDB with CA atoms along x-axis.

    Returns metadata dict with provenance and warnings.
    """
    seq = (sequence or "").strip().upper()
    if not seq:
        return {"success": False, "error": "empty_sequence"}

    invalid = sorted({c for c in seq if c not in VALID_AAS})
    if invalid:
        return {"success": False, "error": f"invalid_residues: {invalid}"}

    os.makedirs(os.path.dirname(output_pdb) or ".", exist_ok=True)

    with open(output_pdb, "w") as fh:
        fh.write(_EXTENDED_PEPTIDE_REMARK)
        for i, aa in enumerate(seq):
            atom_idx = i + 1
            res_idx = i + 1
            x = i * _EPS
            aa3 = _AA1TO3.get(aa, "UNK")
            fh.write(
                f"ATOM  {atom_idx:5d}  CA  {aa3:3s} {chain_id}{res_idx:4d}"
                f"    {x:8.3f}{0.0:8.3f}{0.0:8.3f}"
                f"  1.00  0.00           C\n"
            )
        fh.write("TER\nEND\n")

    return {
        "success": True,
        "output_pdb": output_pdb,
        "sequence": seq,
        "chain_id": chain_id,
        "residue_count": len(seq),
        "atom_count": len(seq),
        "structure_type": "extended_peptide_initial_construct",
        "experimental_support": "none",
        "calibration": "uncalibrated",
        "provenance": "computed",
    }


# ═══════════════════════════════════════════════════════════════
# Receptor: chain extraction from antibody PDB
# ═══════════════════════════════════════════════════════════════

def _extract_chain_from_pdb(input_pdb: str, output_pdb: str, chain_id: str) -> Dict[str, Any]:
    """Extract a single chain from a PDB file. Returns metadata."""
    atoms = 0
    residues: set[tuple[str, str, str]] = set()
    chains: set[str] = set()

    with open(input_pdb) as fh_in, open(output_pdb, "w") as fh_out:
        for line in fh_in:
            if line.startswith("ATOM  ") or line.startswith("HETATM"):
                if len(line) >= 22 and line[21:22].strip() == chain_id:
                    fh_out.write(line)
                    atoms += 1
                    resnum = line[22:26].strip()
                    inscode = line[26:27].strip()
                    residues.add((chain_id, resnum, inscode))
                    chains.add(chain_id)
            elif line.startswith("TER"):
                fh_out.write("TER\n")
        fh_out.write("END\n")

    return {
        "output_pdb": output_pdb,
        "chain_id": chain_id,
        "atom_count": atoms,
        "residue_count": len(residues),
        "chain_ids": list(chains),
    }


# ═══════════════════════════════════════════════════════════════
# Public API
# ═══════════════════════════════════════════════════════════════

def prepare_docking_inputs(
    structure_manifest: Dict[str, Any],
    epitope_sequence: str,
    output_dir: str,
    receptor_chain: str = "H",
) -> Dict[str, Any]:
    """Prepare docking inputs from a Phase 3C-3 structure manifest.

    Does NOT run docking.  Produces receptor PDBs, ligand PDB, and
    constraint JSONs for downstream docking backends.

    Args:
        structure_manifest: Output from build_vh_structures().
        epitope_sequence: Target epitope (e.g. "PSAEVWD").
        output_dir: Directory for prepared inputs.
        receptor_chain: Chain ID to extract from antibody PDB.

    Returns:
        Docking input manifest dict.
    """
    os.makedirs(output_dir, exist_ok=True)
    receptors_dir = os.path.join(output_dir, "receptors")
    ligands_dir = os.path.join(output_dir, "ligands")
    constraints_dir = os.path.join(output_dir, "constraints")
    for d in [receptors_dir, ligands_dir, constraints_dir]:
        os.makedirs(d, exist_ok=True)

    candidates = structure_manifest.get("candidates", [])
    receptors: List[Dict[str, Any]] = []
    ligands: List[Dict[str, Any]] = []
    constraints: List[Dict[str, Any]] = []
    skipped = 0
    failed = 0
    prepared = 0

    # ── Ligand preparation (once for all candidates) ──────────
    ligand_pdb = os.path.join(ligands_dir, f"epitope_{epitope_sequence}_ligand.pdb")
    ligand_meta = build_extended_peptide_pdb(epitope_sequence, ligand_pdb)
    if ligand_meta["success"]:
        ligand_meta["eligible_for_docking"] = True
        ligand_meta["interpretation_warning"] = (
            "Peptide conformation is an initial computational construct, "
            "not an experimentally determined structure."
        )
        ligands.append(ligand_meta)

    # ── Receptor preparation (per candidate) ──────────────────
    for c in candidates:
        cid = c.get("candidate_id") or c.get("cdrh3_sequence", f"candidate_{c.get('index', '?')}")
        safe_id = _sanitize_id(cid)
        input_pdb = c.get("output_pdb", "")
        cdrh3 = c.get("cdrh3_sequence", "")
        if "sequence_construction" in c:
            cdrh3 = c["sequence_construction"].get("cdrh3_sequence", cdrh3)

        # Skip mock
        if c.get("mock", False):
            receptors.append({
                "candidate_id": cid, "status": "skipped",
                "reason": "mock_structure", "provenance": "computed",
            })
            skipped += 1
            continue

        # Skip non-eligible
        if not c.get("eligible_for_docking", False):
            receptors.append({
                "candidate_id": cid, "status": "skipped",
                "reason": "not_eligible_for_docking", "provenance": "computed",
            })
            skipped += 1
            continue

        # Validate input PDB
        if not input_pdb or not os.path.isfile(input_pdb):
            receptors.append({
                "candidate_id": cid, "status": "failed",
                "reason": "pdb_missing", "provenance": "computed",
            })
            failed += 1
            continue

        pdb_val = validate_pdb_for_docking(input_pdb)
        if not pdb_val.get("eligible_for_docking", False):
            receptors.append({
                "candidate_id": cid, "status": "skipped",
                "reason": f"pdb_validation_failed: {pdb_val.get('issues', [])}",
                "provenance": "computed",
            })
            skipped += 1
            continue

        # Check requested chain exists
        if receptor_chain not in pdb_val.get("chain_ids", []):
            receptors.append({
                "candidate_id": cid, "status": "failed",
                "reason": f"chain_{receptor_chain}_not_found",
                "available_chains": pdb_val.get("chain_ids", []),
                "provenance": "computed",
            })
            failed += 1
            continue

        # Extract receptor chain
        receptor_pdb = os.path.join(receptors_dir, f"{safe_id}_receptor.pdb")
        try:
            rx_meta = _extract_chain_from_pdb(input_pdb, receptor_pdb, receptor_chain)
            rx_meta["candidate_id"] = cid
            rx_meta["input_pdb"] = input_pdb
            rx_meta["mock"] = False
            rx_meta["eligible_for_docking"] = True
            rx_meta["provenance"] = "computed"
            receptors.append(rx_meta)

            # Constraint
            constraint = {
                "candidate_id": cid,
                "antibody_chain": receptor_chain,
                "ligand_chain": ligand_meta.get("chain_id", "A"),
                "cdrh3_sequence": cdrh3,
                "epitope_sequence": epitope_sequence,
                "preferred_contact_region": "CDRH3",
                "constraint_type": "soft_region_hint",
                "provenance": "computed",
                "calibration": "uncalibrated",
            }
            constraint_path = os.path.join(constraints_dir, f"{safe_id}_constraints.json")
            with open(constraint_path, "w") as fh:
                json.dump(constraint, fh, indent=2)
            constraints.append(constraint)
            prepared += 1
        except Exception as exc:
            receptors.append({
                "candidate_id": cid, "status": "failed",
                "reason": f"receptor_extraction_error: {exc}",
                "provenance": "computed",
            })
            failed += 1

    # ── Build manifest ────────────────────────────────────────
    manifest: Dict[str, Any] = {
        "manifest_version": "3C-4",
        "phase": "Phase 3C-4",
        "capability": "docking_input_preparation",
        "docking_performed": False,
        "calibration": "uncalibrated",
        "provenance": "computed",
        "output_dir": os.path.abspath(output_dir),
        "receptors": receptors,
        "ligands": ligands,
        "constraints": constraints,
        "summary": {
            "input_candidates": len(candidates),
            "prepared_receptors": prepared,
            "prepared_ligands": len(ligands),
            "prepared_constraints": prepared,
            "skipped": skipped,
            "failed": failed,
        },
    }

    manifest_path = os.path.join(output_dir, "docking_input_manifest.json")
    with open(manifest_path, "w") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)

    return manifest
