"""Tool profile manifests — GENERATED by scripts/audit_runtime_tools.py.

MINIMAL_TOOL_MODULES lists the modules loaded by the minimal runtime
profile (competition demo + antibody design pipeline + engine glue).
The full profile loads every attributed Biochat tool module.
Regenerate with: python scripts/audit_runtime_tools.py
"""

MINIMAL_TOOL_MODULES: frozenset[str] = frozenset({
    'biochat.tool.antibody_design',
    'biochat.tool.database',
    'biochat.tool.literature',
    'biochat.tool.protocols',
    'biochat.tool.support_tools',
})
